# Generated by Django 6.0.7 on 2026-07-14 07:01

import django.db.models.deletion
from django.db import migrations, models


def copy_client_contracts(apps, schema_editor):
    Client = apps.get_model('webCom', 'Client')
    Contract = apps.get_model('webCom', 'Contract')

    contracts = []
    for client in Client.objects.all():
        contracts.append(
            Contract(
                client_id=client.client_id,
                contract_start_date=client.contract_start_date,
                contract_end_date=client.contract_end_date,
                contract_status=client.contract_status,
                created_at=client.created_at,
                updated_at=client.updated_at,
            )
        )

    Contract.objects.bulk_create(contracts)


def restore_client_contracts(apps, schema_editor):
    Client = apps.get_model('webCom', 'Client')
    Contract = apps.get_model('webCom', 'Contract')

    for client in Client.objects.all():
        contract = Contract.objects.filter(client_id=client.client_id).order_by('contract_start_date').first()
        if contract:
            client.contract_start_date = contract.contract_start_date
            client.contract_end_date = contract.contract_end_date
            client.contract_status = contract.contract_status
            client.save(update_fields=['contract_start_date', 'contract_end_date', 'contract_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('contract_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='webCom.client')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.RunPython(copy_client_contracts, restore_client_contracts),
        migrations.RemoveField(
            model_name='client',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract_start_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract_status',
        ),
    ]
