# Generated by Django 6.0.7 on 2026-07-14 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0002_remove_client_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_of_guards',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='contract',
            name='number_of_guards_per_shift',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
