# Generated by Django 6.0.7 on 2026-07-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0003_contract_contract_value_contract_number_of_guards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='webCom.contract'),
        ),
    ]
