# Generated by Django 6.0.7 on 2026-07-14 08:24

import django.core.validators
from django.db import migrations, models


def copy_existing_guard_count_to_day_shift(apps, schema_editor):
    Contract = apps.get_model('webCom', 'Contract')
    for contract in Contract.objects.all():
        contract.day_shift_guards = contract.number_of_guards
        contract.night_shift_guards = 0
        contract.save(update_fields=['day_shift_guards', 'night_shift_guards'])

class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0005_contract_rate_per_guard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='day_shift_guards',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='contract',
            name='night_shift_guards',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(copy_existing_guard_count_to_day_shift, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contract',
            name='number_of_guards',
            field=models.IntegerField(default=1, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]

