# Generated by Django 6.0.7 on 2026-07-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0006_contract_day_shift_guards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='number_of_guards_per_shift',
        ),
    ]
