# Generated by Django 6.0.7 on 2026-07-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0007_remove_contract_number_of_guards_per_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdeliverable',
            name='item_name',
            field=models.CharField(choices=[('gun', 'Gun'), ('radio', 'Radio'), ('walk_through_detector', 'Walk Through Detector'), ('dog', 'Dog'), ('vehicle', 'Vehicle'), ('uniform', 'Uniform'), ('other', 'Other')], max_length=100),
        ),
    ]
