# Generated by Django 6.0.7 on 2026-07-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0008_alter_contractdeliverable_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='site',
            name='state',
        ),
    ]
