# Generated by Django 6.0.7 on 2026-07-14 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0009_remove_site_notes_remove_site_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='activity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='day_shift_guards',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='site',
            name='night_shift_guards',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='site',
            name='rate_per_guard',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
