# Generated by Django 6.0.7 on 2026-07-14 10:06

from django.db import migrations, models


def recalculate_shift_types(apps, schema_editor):
    Shift = apps.get_model('webCom', 'Shift')
    for shift in Shift.objects.all():
        shift.shift_type = 'day' if 7 <= shift.start_time.hour < 18 else 'night'
        shift.save(update_fields=['shift_type'])

class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0010_site_activity_site_day_shift_guards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='description',
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], editable=False, max_length=20),
        ),
        migrations.RunPython(recalculate_shift_types, migrations.RunPython.noop),
    ]

