# Generated by Django 6.0.7 on 2026-07-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0011_remove_shift_description_alter_shift_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='webCom.site'),
        ),
    ]
