# Generated by Django 6.0.7 on 2026-07-14 10:29

from django.db import migrations, models


def populate_contract_numbers(apps, schema_editor):
    Contract = apps.get_model("webCom", "Contract")
    for contract in Contract.objects.filter(contract_number__isnull=True):
        contract.contract_number = f"CON-{contract.contract_id:06d}"
        contract.save(update_fields=["contract_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0012_alter_shift_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.RunPython(populate_contract_numbers, migrations.RunPython.noop),
    ]

