# Generated by Django 6.0.7 on 2026-07-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0013_contract_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attended_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_attendance_records', to='webCom.guard'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='webCom.deployment'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scheduled_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_attendance_records', to='webCom.guard'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='webCom.shift'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='webCom.site'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='webCom.guard'),
        ),
    ]
