# Generated by Django 6.0.7 on 2026-07-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0015_remove_shift_shift_date_remove_shift_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='site',
            name='rate_per_guard',
        ),
        migrations.RemoveField(
            model_name='site',
            name='security_level',
        ),
        migrations.AlterField(
            model_name='site',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='webCom.client'),
        ),
    ]
