# Generated by Django 6.0.7 on 2026-07-14 14:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def preserve_existing_asset_sites(apps, schema_editor):
    Asset = apps.get_model('webCom', 'Asset')
    AssetAssignment = apps.get_model('webCom', 'AssetAssignment')
    for asset in Asset.objects.exclude(site_id__isnull=True):
        AssetAssignment.objects.create(
            asset=asset,
            site_id=asset.site_id,
            quantity=asset.quantity,
            status='assigned',
            notes='Created from previous asset site assignment.',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0016_remove_site_activity_remove_site_rate_per_guard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('uniform', 'Uniform'), ('gun', 'Gun'), ('weapon', 'Weapon'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='webCom.asset')),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='webCom.deployment')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments', to='webCom.employee')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='webCom.guard')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='webCom.site')),
            ],
            options={
                'db_table': 'asset_assignments',
            },
        ),
        migrations.RunPython(preserve_existing_asset_sites, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='asset',
            name='site',
        ),
    ]
