# Generated by Django 6.0.7 on 2026-07-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0017_remove_asset_site_alter_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Serial Number'),
        ),
    ]
