# Generated by Django 6.0.7 on 2026-07-14 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0018_asset_asset_name_alter_asset_asset_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('authority_group', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='webCom.incident')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_notifications', to='webCom.employee')),
            ],
            options={
                'db_table': 'incident_notifications',
                'unique_together': {('incident', 'recipient', 'authority_group')},
            },
        ),
    ]
