# Generated by Django 6.0.7 on 2026-07-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0019_incidentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='closed_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='conclusion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='corrective_action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='immediate_action_taken',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='investigation_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incident_investigations', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='incident',
            name='investigation_findings',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='notification_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='occurrence_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('notified', 'Authorities Notified'), ('investigating', 'Under Investigation'), ('action_taken', 'Action Taken'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=30),
        ),
    ]
