# Generated by Django 6.0.7 on 2026-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0020_incident_closed_at_incident_closed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NSSF Number'),
        ),
    ]
