# Generated by Django 6.0.7 on 2026-07-15 11:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_employee_roles(apps, schema_editor):
    Employee = apps.get_model('webCom', 'Employee')
    Guard = apps.get_model('webCom', 'Guard')
    Supervisor = apps.get_model('webCom', 'Supervisor')
    Role = apps.get_model('webCom', 'Role')
    Salary = apps.get_model('webCom', 'Salary')

    guard_profiles = {
        guard.employee_id: guard
        for guard in Guard.objects.all()
    }
    supervisor_profiles = {
        supervisor.employee_id: supervisor
        for supervisor in Supervisor.objects.all()
    }
    role_names = {
        str(role.pk): (role.role_name or '').lower()
        for role in Role.objects.all()
    }

    salary_scales = {
        'security_guard': Decimal('650000.00'),
        'site_supervisor': Decimal('900000.00'),
        'regional_supervisor': Decimal('1200000.00'),
        'operations_officer': Decimal('1100000.00'),
        'hr_officer': Decimal('1000000.00'),
        'finance_officer': Decimal('1000000.00'),
        'administrator': Decimal('950000.00'),
    }

    for employee in Employee.objects.all():
        old_role_name = role_names.get(str(employee.role), str(employee.role).lower())
        if employee.pk in guard_profiles:
            guard = guard_profiles[employee.pk]
            employee.role = 'guard'
            employee.position = 'security_guard'
            employee.department = 'operations'
            employee.qualification = guard.qualification
            employee.armed_status = guard.armed_status
        elif employee.pk in supervisor_profiles:
            supervisor = supervisor_profiles[employee.pk]
            employee.role = 'supervisor'
            employee.position = 'site_supervisor'
            employee.department = 'operations'
            employee.authority_level = supervisor.authority_level
        elif 'hr' in old_role_name:
            employee.role = 'hr_officer'
            employee.position = 'hr_officer'
            employee.department = 'hr'
        elif 'finance' in old_role_name:
            employee.role = 'finance_officer'
            employee.position = 'finance_officer'
            employee.department = 'finance'
        elif 'manager' in old_role_name:
            employee.role = 'manager'
            employee.position = 'operations_officer'
            employee.department = 'operations'
        elif 'admin' in old_role_name:
            employee.role = 'administrator'
            employee.position = 'administrator'
            employee.department = 'admin'
        else:
            employee.role = 'operations_officer'
            employee.position = 'operations_officer'
            employee.department = 'operations'

        employee.salary_scale = salary_scales.get(employee.position, Decimal('650000.00'))
        employee.save(update_fields=['role', 'position', 'department', 'salary_scale', 'qualification', 'armed_status', 'authority_level'])

    for salary in Salary.objects.select_related('employee'):
        if salary.employee.salary_scale:
            salary.basic_salary = salary.employee.salary_scale
            salary.save(update_fields=['basic_salary'])

class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0021_employee_nssf_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='armed_status',
            field=models.CharField(blank=True, choices=[('armed', 'Armed'), ('unarmed', 'Unarmed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='authority_level',
            field=models.CharField(blank=True, choices=[('site', 'Site Level'), ('regional', 'Regional Level'), ('national', 'National Level')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('operations', 'Operations'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('admin', 'Administration')], default='operations', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('security_guard', 'Security Guard'), ('site_supervisor', 'Site Supervisor'), ('regional_supervisor', 'Regional Supervisor'), ('operations_officer', 'Operations Officer'), ('hr_officer', 'HR Officer'), ('finance_officer', 'Finance Officer'), ('administrator', 'Administrator')], default='security_guard', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Security'), ('advanced', 'Advanced Security'), ('specialized', 'Specialized Training')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_scale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_asset_assignments', to='webCom.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attended_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_attendance_records', to='webCom.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='scheduled_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_attendance_records', to='webCom.employee'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard_deployments', to='webCom.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('guard', 'Guard'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('operations_officer', 'Operations Officer'), ('hr_officer', 'HR Officer'), ('finance_officer', 'Finance Officer'), ('administrator', 'Administrator')], default='guard', max_length=50),
        ),
        migrations.RunPython(backfill_employee_roles, migrations.RunPython.noop),
    ]
