# Generated by Django 6.0.7 on 2026-07-17 16:08

import django.db.models.deletion
from django.db import migrations, models


def copy_deployment_data(apps, schema_editor):
    Deployment = apps.get_model('webCom', 'Deployment')
    Site = apps.get_model('webCom', 'Site')

    for deployment in Deployment.objects.exclude(site_id__isnull=True):
        if deployment.client_id is None:
            site = Site.objects.filter(pk=deployment.site_id).first()
            if site and site.client_id:
                deployment.client_id = site.client_id
                deployment.save(update_fields=['client'])
        if deployment.guard_id:
            site = Site.objects.filter(pk=deployment.site_id).first()
            if site:
                site.guards.add(deployment.guard_id)


def noop_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0022_employee_armed_status_employee_authority_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='webCom.client'),
        ),
        migrations.AddField(
            model_name='site',
            name='guards',
            field=models.ManyToManyField(blank=True, related_name='assigned_sites', to='webCom.employee'),
        ),
        migrations.RunPython(copy_deployment_data, noop_reverse),
    ]

