# Generated by Codex on 2026-07-18

from django.db import migrations, models


def backfill_employee_numbers(apps, schema_editor):
    Employee = apps.get_model("webCom", "Employee")
    for employee in Employee.objects.order_by("employee_id"):
        employee.employee_number = employee.employee_id
        employee.save(update_fields=["employee_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("webCom", "0023_deployment_client_site_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_number",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="Employee Number",
            ),
        ),
        migrations.RunPython(backfill_employee_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employee",
            name="employee_number",
            field=models.PositiveIntegerField(
                blank=True,
                unique=True,
                verbose_name="Employee Number",
            ),
        ),
    ]