# Generated by Codex on 2026-07-18

from datetime import date, timedelta
from decimal import Decimal

from django.db import migrations, models


def months_worked(hire_date):
    if not hire_date:
        return 0
    today = date.today()
    months = (today.year - hire_date.year) * 12 + today.month - hire_date.month
    if today.day < hire_date.day:
        months -= 1
    return max(months, 0)


def guard_seniority_code(hire_date):
    months = months_worked(hire_date)
    if months < 6:
        return "TE"
    if months < 60:
        return "PE"
    if months < 108:
        return "P"
    return "SENIOR"


def daily_rate(employee):
    if employee.role == "guard":
        guard_rates = {
            "TE": Decimal("9000.00"),
            "PE": Decimal("10500.00"),
            "P": Decimal("12000.00"),
            "SENIOR": Decimal("20000.00"),
        }
        return guard_rates[guard_seniority_code(employee.hire_date)]
    if employee.role == "supervisor":
        return Decimal("30000.00")
    return Decimal("30000.00")


def salary_period_dates(pay_period):
    today = date.today()
    if pay_period == "weekly":
        start_date = today - timedelta(days=today.weekday())
        return start_date, start_date + timedelta(days=6)
    if pay_period == "biweekly":
        week_start = today - timedelta(days=today.weekday())
        start_date = week_start if week_start.isocalendar().week % 2 == 0 else week_start - timedelta(days=7)
        return start_date, start_date + timedelta(days=13)
    start_date = today.replace(day=1)
    next_month = (start_date.replace(day=28) + timedelta(days=4)).replace(day=1)
    return start_date, next_month - timedelta(days=1)

def refresh_employee_daily_rates(apps, schema_editor):
    Employee = apps.get_model("webCom", "Employee")
    Salary = apps.get_model("webCom", "Salary")
    Attendance = apps.get_model("webCom", "Attendance")
    for employee in Employee.objects.all():
        employee.salary_scale = daily_rate(employee)
        employee.save(update_fields=["salary_scale"])
    for salary in Salary.objects.select_related("employee"):
        start_date, end_date = salary_period_dates(salary.pay_period)
        shifts_worked = Attendance.objects.filter(
            attended_guard_id=salary.employee_id,
            date__range=(start_date, end_date),
        ).count()
        salary.basic_salary = salary.employee.salary_scale * shifts_worked
        salary.save(update_fields=["basic_salary"])


class Migration(migrations.Migration):

    dependencies = [
        ("webCom", "0024_employee_employee_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_number",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                unique=True,
                verbose_name="Employee Number",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary_scale",
            field=models.DecimalField(
                "Daily Rate",
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
            ),
        ),
        migrations.RunPython(refresh_employee_daily_rates, migrations.RunPython.noop),
    ]