# Generated by Codex on 2026-07-18

from datetime import date

from django.db import migrations, models


def months_worked(hire_date):
    if not hire_date:
        return 0
    today = date.today()
    months = (today.year - hire_date.year) * 12 + today.month - hire_date.month
    if today.day < hire_date.day:
        months -= 1
    return max(months, 0)


def seniority_code(hire_date):
    months = months_worked(hire_date)
    if months < 6:
        return "TE"
    if months < 60:
        return "PE"
    if months < 108:
        return "P"
    return "SENIOR"


def backfill_employee_number_codes(apps, schema_editor):
    Employee = apps.get_model("webCom", "Employee")
    counters = {}
    for employee in Employee.objects.order_by("employee_id"):
        prefix = seniority_code(employee.hire_date)
        counters[prefix] = counters.get(prefix, 0) + 1
        employee.employee_number = f"{prefix}{counters[prefix]:03d}"
        employee.save(update_fields=["employee_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("webCom", "0025_employee_daily_rate_seniority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_number",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Employee Number",
            ),
        ),
        migrations.RunPython(backfill_employee_number_codes, migrations.RunPython.noop),
    ]