# Generated by Codex on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webCom", "0026_employee_number_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="training_type",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("refresher", "Refresher"),
                    ("promotional_course", "Promotional Course"),
                    ("management_training", "Management Training"),
                ],
                default="refresher",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="recruit",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="training",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainings",
                to="webCom.employee",
            ),
        ),
    ]