# Generated by Codex on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webCom", "0027_training_type_recruit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="training_name",
            field=models.CharField(
                choices=[
                    ("guarding_training", "Guarding Training"),
                    ("supervision_course", "Supervision Course"),
                    ("managers_course", "Managers Course"),
                    ("iso_training", "ISO Training"),
                ],
                default="guarding_training",
                max_length=50,
            ),
        ),
    ]