# Generated by Codex on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webCom", "0028_alter_training_training_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="provider",
            field=models.CharField(
                default="TURYANS SECURITY COMPANY (U) LIMITED",
                max_length=255,
            ),
        ),
    ]