# Generated by Codex on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webCom", "0029_alter_training_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="end_date",
            field=models.DateField("Date of Completion"),
        ),
    ]