# Generated by Codex on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone




def backfill_site_guard_deployment_areas(apps, schema_editor):
    DeploymentArea = apps.get_model("webCom", "DeploymentArea")
    Site = apps.get_model("webCom", "Site")
    Deployment = apps.get_model("webCom", "Deployment")
    for site in Site.objects.all():
        first_deployment = Deployment.objects.filter(site=site).order_by("start_date").first()
        start_date = first_deployment.start_date if first_deployment else timezone.localdate()
        for employee in site.guards.all():
            if employee.role not in ("guard", "supervisor"):
                continue
            DeploymentArea.objects.get_or_create(
                employee=employee,
                site=site,
                start_date=start_date,
                defaults={"status": "active"},
            )
class Migration(migrations.Migration):

    dependencies = [
        ("webCom", "0030_alter_training_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentArea",
            fields=[
                ("deployment_area_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("transfer_notes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deployment_areas", to="webCom.employee")),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deployment_areas", to="webCom.site")),
                ("transferred_by_hr_manager", models.ForeignKey(blank=True, limit_choices_to={"role__in": ["hr_officer", "manager"]}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_deployment_transfers", to="webCom.employee")),
            ],
            options={
                "verbose_name": "Deployment Area",
                "verbose_name_plural": "Deployment Areas",
                "db_table": "deployment_areas",
            },
        ),
        migrations.RunPython(backfill_site_guard_deployment_areas, migrations.RunPython.noop),
    ]