# Generated by Codex on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_REGION = "Central Region"


def backfill_regions(apps, schema_editor):
    Region = apps.get_model("webCom", "Region")
    Site = apps.get_model("webCom", "Site")
    DeploymentArea = apps.get_model("webCom", "DeploymentArea")

    default_region, _created = Region.objects.get_or_create(region_name=DEFAULT_REGION)
    Site.objects.filter(region__isnull=True).update(region=default_region)
    for area in DeploymentArea.objects.select_related("site"):
        if area.region_id:
            continue
        area.region = area.site.region if area.site_id and area.site.region_id else default_region
        area.save(update_fields=["region"])


class Migration(migrations.Migration):

    dependencies = [
        ("webCom", "0031_deploymentarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("region_id", models.AutoField(primary_key=True, serialize=False)),
                ("region_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "db_table": "regions",
            },
        ),
        migrations.AddField(
            model_name="site",
            name="region",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sites", to="webCom.region"),
        ),
        migrations.AddField(
            model_name="deploymentarea",
            name="region",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="deployment_areas", to="webCom.region"),
        ),
        migrations.RunPython(backfill_regions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="deploymentarea",
            name="region",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deployment_areas", to="webCom.region"),
        ),
        migrations.RemoveField(
            model_name="deploymentarea",
            name="site",
        ),
    ]