# Generated by Django 6.0.7 on 2026-07-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0032_region_deploymentarea_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('o_level', 'O Level'), ('a_level', 'A Level'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('other', 'Other')], default='', max_length=50, verbose_name='Academic Qualification'),
        ),
    ]
