# Generated by Django 6.0.7 on 2026-07-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0033_alter_employee_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRecovery',
            fields=[
                ('recovery_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='webCom.advance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_recoveries', to='webCom.employee')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_recoveries', to='webCom.salary')),
            ],
            options={
                'db_table': 'advance_recoveries',
                'constraints': [models.UniqueConstraint(fields=('advance', 'salary', 'period_start_date', 'period_end_date'), name='unique_advance_recovery_per_salary_period')],
            },
        ),
    ]
