# Generated by Django 6.0.7 on 2026-07-18 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0034_advancerecovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
