# Generated by Django 6.0.7 on 2026-07-18 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0035_advance_installment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
