# Generated by Django 6.0.7 on 2026-07-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0036_alter_advance_installment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerecovery',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='advancerecovery',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
