# Generated by Django 6.0.7 on 2026-07-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0037_advancerecovery_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
