# Generated by Django 6.0.7 on 2026-07-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0041_invoice_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leave',
            name='hr_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='operations_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leave',
            name='operations_verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='leave',
            name='operations_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_verified_leaves', to='webCom.employee'),
        ),
    ]
