# Generated by Django 6.0.7 on 2026-07-20 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0043_update_admin_employee_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinary_action',
            name='concluded_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='conclusion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_cases_handled', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='hearing_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='investigation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='offence_committed',
            field=models.CharField(default='Unspecified offence', max_length=255),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='offence_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('verbal_warning', 'Verbal Warning'), ('written_warning', 'Written Warning'), ('suspension', 'Suspension'), ('termination', 'Termination'), ('cleared', 'Cleared'), ('other', 'Other')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_reports_made', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Under Investigation'), ('hearing', 'Hearing Scheduled'), ('action_taken', 'Action Taken'), ('concluded', 'Concluded')], default='reported', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='disciplinary_action',
            name='steps_taken',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='disciplinary_action',
            name='action_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='disciplinary_action',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='disciplinary_action',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
