# Generated by Django 6.0.7 on 2026-07-20 22:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0044_disciplinary_action_concluded_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disciplinary_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='webCom.disciplinary_action')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_notifications', to='webCom.employee')),
            ],
            options={
                'db_table': 'disciplinary_notifications',
                'constraints': [models.UniqueConstraint(fields=('disciplinary_action', 'recipient'), name='unique_disciplinary_feedback_notification')],
            },
        ),
    ]
