# Generated by Django 6.0.7 on 2026-07-20 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0047_update_supervisor_employee_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymee',
            options={'verbose_name': 'Receivable', 'verbose_name_plural': 'Receivables'},
        ),
        migrations.AddField(
            model_name='paymee',
            name='client',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='webCom.client'),
        ),
        migrations.AddField(
            model_name='paymee',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
        migrations.AddField(
            model_name='paymee',
            name='due_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='paymee',
            name='last_payment_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='paymee',
            name='payment_terms',
            field=models.CharField(default='Due on receipt', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('overpaid', 'Overpaid'), ('cancelled', 'Cancelled')], default='pending', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='paymee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
