# Generated by Django 6.0.7 on 2026-07-20 23:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models

def seed_existing_budget_accountability(apps, schema_editor):
    Budget = apps.get_model('webCom', 'Budget')
    for budget in Budget.objects.all().order_by('budget_id'):
        fiscal_year = budget.year or budget.fiscal_year or 2026
        update_fields = []
        if not budget.fiscal_year:
            budget.fiscal_year = fiscal_year
            update_fields.append('fiscal_year')
        if not budget.budget_code:
            budget.budget_code = f"BUD-{fiscal_year}-{budget.budget_id:05d}"
            update_fields.append('budget_code')
        if not budget.budget_title or budget.budget_title == 'Department Budget':
            budget.budget_title = f"{budget.get_department_display()} Budget {fiscal_year}"
            update_fields.append('budget_title')
        if not budget.requested_amount:
            budget.requested_amount = budget.allocated_amount
            update_fields.append('requested_amount')
        if update_fields:
            budget.save(update_fields=update_fields)


def reverse_seed_existing_budget_accountability(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0049_refresh_paymee_receivables'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='accountability_status',
            field=models.CharField(choices=[('not_due', 'Not Due'), ('pending_expense', 'Pending Expense Record'), ('partially_accounted', 'Partially Accounted'), ('accounted', 'Fully Accounted'), ('over_spent', 'Over Spent')], default='not_due', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='budget',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_requisitions_approved', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_category',
            field=models.CharField(choices=[('payroll', 'Payroll'), ('operations', 'Operations'), ('training', 'Training'), ('equipment', 'Equipment'), ('admin', 'Administration'), ('other', 'Other')], default='operations', max_length=50),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_code',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_title',
            field=models.CharField(default='Department Budget', max_length=255),
        ),
        migrations.AddField(
            model_name='budget',
            name='fiscal_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='budget',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_end',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='budget',
            name='period_start',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='budget',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='budget',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_requisitions_requested', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='budget',
            name='requisition_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='budget',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_requisitions_verified', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='webCom.budget'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='recorded', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_verified', to='webCom.employee'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(seed_existing_budget_accountability, reverse_seed_existing_budget_accountability),
        migrations.CreateModel(
            name='BudgetNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_group', models.CharField(max_length=50)),
                ('notification_type', models.CharField(choices=[('low_balance', 'Low Balance'), ('missing_expense', 'Missing Expense Accountability')], max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_note', models.CharField(blank=True, default='', max_length=255)),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='webCom.budget')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_notifications', to='webCom.employee')),
            ],
            options={
                'db_table': 'budget_notifications',
                'constraints': [models.UniqueConstraint(fields=('budget', 'recipient', 'notification_type'), name='unique_budget_notification_per_recipient')],
            },
        ),
    ]


