# Generated by Django 6.0.7 on 2026-07-20 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0051_expense_accountability_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_submitted', to='webCom.employee'),
        ),
    ]
