# Generated by Django 6.0.7 on 2026-07-21 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0052_alter_expense_spent_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedLink',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(default='Partner', max_length=80)),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'associated_links',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('summary', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_events',
                'ordering': ['-event_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('department', models.CharField(default='Operations', max_length=80)),
                ('location', models.CharField(default='Kampala', max_length=160)),
                ('employment_type', models.CharField(default='Full-time', max_length=80)),
                ('summary', models.TextField()),
                ('requirements', models.TextField(blank=True, default='')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_postings',
                'ordering': ['-posted_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteAdvertisement',
            fields=[
                ('advert_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('placement', models.CharField(default='Homepage', max_length=80)),
                ('message', models.TextField()),
                ('call_to_action', models.CharField(blank=True, default='', max_length=80)),
                ('target_url', models.CharField(blank=True, default='', max_length=255)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_advertisements',
                'ordering': ['-starts_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteResource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('resource_type', models.CharField(default='Guide', max_length=80)),
                ('summary', models.TextField()),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'website_resources',
                'ordering': ['resource_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_mode', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='online', max_length=20)),
                ('applicant_name', models.CharField(max_length=180)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('qualification', models.CharField(blank=True, default='', max_length=180)),
                ('experience_summary', models.TextField(blank=True, default='')),
                ('cover_note', models.TextField(blank=True, default='')),
                ('resume', models.FileField(blank=True, null=True, upload_to='job_applications/')),
                ('status', models.CharField(choices=[('received', 'Received'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('hired', 'Hired'), ('declined', 'Declined')], default='received', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_job_applications', to='webCom.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='webCom.jobposting')),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
