# Generated by Django 6.0.7 on 2026-07-23 17:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0054_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('deduction_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('loan', 'Loan'), ('medical', 'Medical'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_deductions', to='webCom.employee')),
            ],
            options={
                'db_table': 'payroll_deductions',
                'ordering': ['employee__employee_number', 'category', 'start_date'],
            },
        ),
    ]
