# Generated by Django 6.0.7 on 2026-07-23 17:24

from django.db import migrations, models


def backfill_invoice_numbers(apps, schema_editor):
    Invoice = apps.get_model("webCom", "Invoice")
    for invoice in Invoice.objects.order_by("invoice_id"):
        if not invoice.invoice_number:
            invoice.invoice_number = f"INV{invoice.invoice_id:03d}"
            invoice.save(update_fields=["invoice_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0055_payrolldeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billable_products',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='webCom.contractdeliverable'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(backfill_invoice_numbers, migrations.RunPython.noop),
    ]
