# Generated by Django 6.0.7 on 2026-07-23 17:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0056_invoice_billable_products_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18, help_text='Uganda VAT rate percentage applied to taxable invoice charges.', max_digits=5),
        ),
        migrations.CreateModel(
            name='InvoiceBillableItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(choices=[('gun', 'Gun'), ('radio', 'Radio'), ('walk_through_detector', 'Walk Through Detector'), ('metal_detector', 'Metal Detector'), ('vehicle', 'Vehicle'), ('dog', 'Dog'), ('other', 'Other')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(default='item(s)', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('taxable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisional_items', to='webCom.invoice')),
            ],
            options={
                'db_table': 'invoice_billable_items',
            },
        ),
    ]
