# Generated by Django 6.0.7 on 2026-07-23 18:51

from django.db import migrations, models


def seed_invoice_billable_item_prices(apps, schema_editor):
    Price = apps.get_model("webCom", "InvoiceBillableItemPrice")
    defaults = {
        "gun": "50000.00",
        "radio": "50000.00",
        "walk_through_detector": "250000.00",
        "metal_detector": "250000.00",
        "vehicle": "100000.00",
        "dog": "80000.00",
        "other": "0.00",
    }
    for item_name, unit_price in defaults.items():
        Price.objects.get_or_create(item_name=item_name, defaults={"unit_price": unit_price, "taxable": True, "active": True})


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0057_invoice_tax_amount_invoice_tax_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBillableItemPrice',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(choices=[('gun', 'Gun'), ('radio', 'Radio'), ('walk_through_detector', 'Walk Through Detector'), ('metal_detector', 'Metal Detector'), ('vehicle', 'Vehicle'), ('dog', 'Dog'), ('other', 'Other')], max_length=100, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provisional Billable Item Price',
                'verbose_name_plural': 'Provisional Billable Item Prices',
                'db_table': 'invoice_billable_item_prices',
            },
        ),
        migrations.RunPython(seed_invoice_billable_item_prices, migrations.RunPython.noop),
    ]



