# Generated by Django 6.0.7 on 2026-07-26 09:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0059_seed_invoice_billable_item_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('tax_identification_number', models.CharField(blank=True, default='', max_length=80)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('due_diligence_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequisition',
            fields=[
                ('requisition_id', models.AutoField(primary_key=True, serialize=False)),
                ('requisition_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('payroll', 'Payroll'), ('operations', 'Operations'), ('training', 'Training'), ('equipment', 'Equipment'), ('admin', 'Administration'), ('other', 'Other')], default='operations', max_length=50)),
                ('description', models.TextField()),
                ('department', models.CharField(choices=[('operations', 'Operations'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('admin', 'Administration')], default='operations', max_length=50)),
                ('required_date', models.DateField()),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('justification', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to Purchase Order'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requisitions', to='webCom.budget')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requisitions_requested', to='webCom.employee')),
            ],
            options={
                'db_table': 'procurement_requisitions',
                'ordering': ['-created_at', '-requisition_id'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_approvals', to='webCom.employee')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='webCom.procurementrequisition')),
            ],
            options={
                'db_table': 'procurement_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_delivery_date', models.DateField()),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('payment_terms', models.CharField(choices=[('on_delivery', 'On Delivery'), ('net_7', 'Net 7'), ('net_15', 'Net 15'), ('net_30', 'Net 30')], default='net_15', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('invoiced', 'Invoiced'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_prepared', to='webCom.employee')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='webCom.procurementrequisition')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='webCom.supplier')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-order_date', '-purchase_order_id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('grn_id', models.AutoField(primary_key=True, serialize=False)),
                ('grn_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_note_number', models.CharField(blank=True, default='', max_length=100)),
                ('quantity_summary', models.CharField(max_length=255)),
                ('condition_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_inspection', 'Pending Inspection'), ('accepted', 'Accepted'), ('partially_accepted', 'Partially Accepted'), ('rejected', 'Rejected')], default='pending_inspection', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_received', to='webCom.employee')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='webCom.purchaseorder')),
            ],
            options={
                'db_table': 'goods_received_notes',
                'ordering': ['-received_date', '-grn_id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('supplier_invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('received', 'Received'), ('matched', 'Three-Way Matched'), ('approved', 'Approved for Payment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='received', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices_approved', to='webCom.employee')),
                ('goods_received_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='webCom.goodsreceivednote')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='webCom.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='webCom.supplier')),
            ],
            options={
                'db_table': 'supplier_invoices',
                'ordering': ['-invoice_date', '-supplier_invoice_id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('supplier_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], max_length=50)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_made', to='webCom.employee')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='webCom.supplierinvoice')),
            ],
            options={
                'db_table': 'supplier_payments',
                'ordering': ['-payment_date', '-supplier_payment_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(fields=('supplier', 'invoice_number'), name='unique_supplier_invoice_number'),
        ),
    ]
