# Generated by Django 6.0.7 on 2026-07-26 10:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0060_supplier_procurementrequisition_procurementapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequisition',
            name='approval_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requisitions_to_approve', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='procurementrequisition',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_procurement_requisitions', to='webCom.supplier'),
        ),
        migrations.AddField(
            model_name='procurementrequisition',
            name='supplier_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequisition',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requisitions_to_view', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_approved', to='webCom.employee'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='procurementrequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('supplier_contacted', 'Supplier Contacted'), ('proforma_received', 'Proforma Received'), ('converted', 'LPO Generated'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='ProcurementNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_group', models.CharField(max_length=50)),
                ('notification_type', models.CharField(choices=[('requisition_submitted', 'Requisition Submitted'), ('requisition_approved', 'Requisition Approved'), ('requisition_rejected', 'Requisition Rejected'), ('supplier_contacted', 'Supplier Contacted'), ('lpo_generated', 'LPO Generated'), ('goods_received', 'Goods Received'), ('payment_initiated', 'Payment Initiated'), ('payment_paid', 'Payment Paid')], max_length=40)),
                ('related_model', models.CharField(blank=True, default='', max_length=80)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_notifications', to='webCom.employee')),
            ],
            options={
                'db_table': 'procurement_notifications',
                'ordering': ['-notified_at', '-notification_id'],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'notification_type', 'related_model', 'related_object_id'), name='unique_procurement_notification')],
            },
        ),
        migrations.CreateModel(
            name='SupplierProformaInvoice',
            fields=[
                ('proforma_id', models.AutoField(primary_key=True, serialize=False)),
                ('proforma_number', models.CharField(max_length=100)),
                ('proforma_date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('delivery_terms', models.CharField(blank=True, default='', max_length=255)),
                ('payment_terms', models.CharField(choices=[('on_delivery', 'On Delivery'), ('net_7', 'Net 7'), ('net_15', 'Net 15'), ('net_30', 'Net 30')], default='net_15', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoice', to='webCom.purchaseorder')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='webCom.procurementrequisition')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='webCom.supplier')),
            ],
            options={
                'db_table': 'supplier_proforma_invoices',
                'ordering': ['-proforma_date', '-proforma_id'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'proforma_number'), name='unique_supplier_proforma_number')],
            },
        ),
    ]
