# Generated by Django 6.0.7 on 2026-07-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0062_alter_supplierproformainvoice_subtotal_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierproformainvoice',
            name='unique_supplier_proforma_number',
        ),
        migrations.AddField(
            model_name='supplierproformainvoice',
            name='supplier_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplierproformainvoice',
            name='proforma_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='supplierproformainvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_reference', ''), _negated=True), fields=('supplier', 'supplier_reference'), name='unique_supplier_reference_number'),
        ),
    ]
