# Generated by Django 6.0.7 on 2026-07-26 10:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0063_remove_supplierproformainvoice_unique_supplier_proforma_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProformaItemPrice',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'supplier_proforma_item_prices',
                'ordering': ['item_name'],
            },
        ),
        migrations.AlterField(
            model_name='supplierproformainvoiceitem',
            name='description',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierproformainvoiceitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proforma_items', to='webCom.supplierproformaitemprice'),
        ),
    ]
