# Generated by Django 6.0.7 on 2026-07-26 11:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0064_supplierproformaitemprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproformaitemprice',
            name='discount_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierproformaitemprice',
            name='max_discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
