# Generated by Django 6.0.7 on 2026-07-27 13:29

from django.db import migrations, models


def backfill_shift_coverage(apps, schema_editor):
    Deployment = apps.get_model('webCom', 'Deployment')
    for deployment in Deployment.objects.select_related('shift'):
        if deployment.shift_id and deployment.shift.shift_type in ('day', 'night'):
            deployment.shift_coverage = deployment.shift.shift_type
            deployment.save(update_fields=['shift_coverage'])


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0065_supplierproformaitemprice_discount_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='shift_coverage',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('day_night', 'Day and Night')], default='day_night', max_length=20),
        ),
        migrations.RunPython(backfill_shift_coverage, migrations.RunPython.noop),
    ]
