# Generated by Django 6.0.7 on 2026-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCom', '0066_deployment_shift_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_reliever',
            field=models.BooleanField(default=False, help_text='Relievers may be assigned to more than one site.', verbose_name='Reliever'),
        ),
    ]
